name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Yarn Install
        run: yarn install
      - name: Yarn Install Frontend
        run: cd design-at-cornell && yarn install
      - name: Build frontend
        run: yarn frontend-build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DESIGNATCORNELL }}'
          projectId: designatcornell
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
